version: "3"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=vik 
      - PORT=5000 
    depends_on:
      - frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
